<?php

$VAR_DEF_LOG_NAO_GRAVAR['SISTEMA']['PRINCIPAL']=true;
$VAR_DEF_LOG_NAO_GRAVAR['SISTEMA']['DEBUG']=true;

$VAR_DEF_LOG_NAO_GRAVAR['USUARIO']['CONSULTA']=true;

$VAR_DEF_LOG_NAO_GRAVAR['MENU']['RELOAD']=true;
$VAR_DEF_LOG_NAO_GRAVAR['MENU']['MONTAR']=true;
$VAR_DEF_LOG_NAO_GRAVAR['MENU']['EXIBIR']=true;
?>